# -*- coding: utf-8 -*-
"""NN_HW1_2(SGD).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFVt7bYYiRbqfg2BmF_7Wf5RZFGVQx-K
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#importing data from google drive
data = pd.read_csv('/content/drive/MyDrive/NN_HW1(data2).csv')
x = data.iloc[:,0]
y = data.iloc[:,1]

a = np.random.rand(1)
b = np.random.rand(1)
c = np.random.rand(1)

learning_rate = 0.01
epochs = 100000
epsilon = 1e-8
beta1 = 0.9
beta2 = 0.999
v_a = 0
v_b = 0
v_c = 0
S_a = 1e-8
S_b = 1e-8
S_c = 1e-8
t = 0

for epoch in range(epochs):

    random_index = np.random.randint(len(x))

    x_i = x[random_index]
    y_i = y[random_index]

    y_pred = a * x_i**2 + b * x_i + c
    error = (y_i - y_pred)

    da =  error * -1 * x_i**2
    db =  error * -1 * x_i
    dc =  error * -1 * 1

    t += 1

    v_a = beta1 * v_a + (1 - beta1) * da
    v_b = beta1 * v_b + (1 - beta1) * db
    v_c = beta1 * v_c + (1 - beta1) * dc

    S_a = max(beta2 * S_a, np.abs(da))
    S_b = max(beta2 * S_b, np.abs(db))
    S_c = max(beta2 * S_c, np.abs(dc))

    v_a_hat = v_a / (1 - beta1**t)
    v_b_hat = v_b / (1 - beta1**t)
    v_c_hat = v_c / (1 - beta1**t)

    a -= (learning_rate / (S_a)) * v_a_hat
    b -= (learning_rate / (S_b)) * v_b_hat
    c -= (learning_rate / (S_c)) * v_c_hat

mse = np.mean((y - (a * x**2 + b * x + c))**2)
print("Trained weight:", a,b,c)
print("adam MSE:", mse)

plt.scatter(x, y, label='Data Points', color='blue')

true_line = a * x**2 + b * x + c
plt.plot(x, true_line, label='True Line', color='red', linestyle='-', linewidth=3)

plt.xlabel('X\nadamax')
plt.ylabel('Y')

plt.legend()
plt.show()

