# -*- coding: utf-8 -*-
"""NN_HW1(SGD).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TIHyPFPliDDnlhhS8ha0Jaqj7QmEL7Vs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#define 100random number
a = 2.0
b = 3.0
n = 100

x = np.linspace(0, 10, n)
noise = np.random.normal(0, 2, n)
y = a * x + b + noise

plt.scatter(x, y, label='Data Points', color='blue')

plt.xlabel('X')
plt.ylabel('Y')

plt.legend()
plt.show()

#exporting data to use for all functions
data = data = list(zip(x, y))
data = pd.DataFrame(data)
data.to_csv('/content/drive/MyDrive/NN_HW1(data).csv', index=False)

#importing data from google drive
data = pd.read_csv('/content/drive/MyDrive/NN_HW1(data).csv')
x = data.iloc[:,0]
y = data.iloc[:,1]

w = np.random.rand(1)
b = np.random.rand(1)

learning_rate = 0.01
epochs = 100000

for epoch in range(epochs):

    random_index = np.random.randint(len(x))

    x_i = x[random_index]
    y_i = y[random_index]

    y_pred = w * x_i + b
    error = (y_i - y_pred)

    dw =  error * -1 * x_i
    db =  error * -1 * 1

    w = w - learning_rate * dw
    b = b - learning_rate * db

mse = np.mean((y - (w * x + b))**2)
print("Trained weight:", w)
print("Trained bias:", b)
print("SGD MSE:", mse)

plt.scatter(x, y, label='Data Points', color='blue')

true_line = w * x + b
plt.plot(x, true_line, label='True Line', color='red', linestyle='-', linewidth=3)

plt.xlabel('X\nSGD')
plt.ylabel('Y')

plt.legend()
plt.show()