# -*- coding: utf-8 -*-
"""NN_HW1_2(SGD).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B8WjyP4HhX4On0yYVVN1vkaD0V1tO7f6
"""

import numpy as np
import matplotlib.pyplot as plt

a = 2.0
b = 3.0
c = 4.0

n = 100

x = np.linspace(-6, 5, n)
noise = np.random.normal(-2, 2, n)
y = a * x**2 + b * x + c + noise

plt.scatter(x, y, label='Data Points', color='blue')

plt.xlabel('X')
plt.ylabel('Y')

plt.legend()
plt.show()

from google.colab import drive
drive.mount('/content/drive')

#exporting data to use for all functions
import pandas as pd
data = data = list(zip(x, y))
data = pd.DataFrame(data)
data.to_csv('/content/drive/MyDrive/NN_HW1(data2).csv', index=False)

#importing data from google drive
data = pd.read_csv('/content/drive/MyDrive/NN_HW1(data2).csv')
x = data.iloc[:,0]
y = data.iloc[:,1]

import numpy as np

a = np.random.rand(1)
b = np.random.rand(1)
c = np.random.rand(1)

learning_rate = 0.001
epochs = 100000

for epoch in range(epochs):

    random_index = np.random.randint(len(x))

    x_i = x[random_index]
    y_i = y[random_index]

    y_pred = a * x_i**2 + b * x_i + c
    error = (y_i - y_pred)

    da =  error * -1 * x_i**2
    db =  error * -1 * x_i
    dc =  error * -1 * 1

    a = a - learning_rate * da
    b = b - learning_rate * db
    c = c - learning_rate * dc

mse = np.mean((y - (a * x**2 + b * x + c))**2)
print("Trained weight:", a,b,c)
print("SGD MSE:", mse)

plt.scatter(x, y, label='Data Points', color='blue')

true_line = a * x**2 + b * x + c
plt.plot(x, true_line, label='True Line', color='red', linestyle='-', linewidth=3)

plt.xlabel('X\nSGD')
plt.ylabel('Y')

plt.legend()
plt.show()

